name: 테스트 실행 및 빌드

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Scream
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Expand-Archive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream

      - name: Run Gradle build
        run: ./gradlew build

      - name: Save test results
        run: |
          mkdir -p test-results
          cp -r ./build/test-results/test/* test-results/
        if: always()
        id: save-results

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results

  publish-results:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Publish test results to PR comments
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/test-results/TEST-*.xml'

      - name: Add comments to failed lines on PR
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/test-results/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
